"""Increase length of token column in MoneyMarketRate

Revision ID: 04e4eb0984f6
Revises: bf60f00425af
Create Date: 2024-07-10 19:33:42.572190

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '04e4eb0984f6'
down_revision = 'bf60f00425af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('money_market_rate', sa.Column('collateral', sa.String(length=50), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('money_market_rate', 'collateral')

    # ### end Alembic commands ###
