"""Add liquidity_reward_rate column to MoneyMarketRate table

Revision ID: 3d473e6a4e34
Revises: 04e4eb0984f6
Create Date: 2024-07-13 10:56:49.903140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d473e6a4e34'
down_revision = '04e4eb0984f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('money_market_rate', sa.Column('liquidity_reward_rate', sa.Float(), nullable=True))
    op.add_column('money_market_rate', sa.Column('liquidity_reward_token', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('money_market_rate', 'liquidity_reward_rate')
    op.drop_column('money_market_rate', 'liquidity_reward_token')


    # ### end Alembic commands ###
