"""Add liquidity_reward_rate column to MoneyMarketRate table

Revision ID: 3d473e6a4e34
Revises: 04e4eb0984f6
Create Date: 2024-07-13 10:56:49.903140

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '3d473e6a4e34'
down_revision = '04e4eb0984f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('money_market_rate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('money_market_rate',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('protocol', sa.VARCHAR(length=15), autoincrement=False, nullable=False),
    sa.Column('token', sa.VARCHAR(length=10), autoincrement=False, nullable=False),
    sa.Column('liquidity_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('borrow_rate', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('chain', sa.VARCHAR(length=20), autoincrement=False, nullable=False),
    sa.Column('tvl', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('collateral', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='money_market_rate_pkey')
    )
    # ### end Alembic commands ###
