"""Initial migration

Revision ID: 5a8bdc0d87c8
Revises:
Create Date: 2024-07-13 13:11:42.642091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5a8bdc0d87c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('money_market_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=50), nullable=False),
    sa.Column('token', sa.String(length=50), nullable=False),
    sa.Column('collateral', sa.String(length=50), nullable=True),
    sa.Column('liquidity_rate', sa.Float(), nullable=False),
    sa.Column('liquidity_reward_rate', sa.Float(), nullable=True),
    sa.Column('liquidity_reward_token', sa.String(length=50), nullable=True),
    sa.Column('borrow_rate', sa.Float(), nullable=False),
    sa.Column('chain', sa.String(length=20), nullable=False),
    sa.Column('tvl', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('money_market_rate')
    # ### end Alembic commands ###
