"""empty message

Revision ID: 68622e49fdcd
Revises: feea6c32a65f
Create Date: 2024-09-17 20:50:02.879344

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68622e49fdcd'
down_revision = 'feea6c32a65f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yield_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('action', sa.String(length=150), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('yield_rate', schema=None) as batch_op:
        batch_op.drop_column('action')

    # ### end Alembic commands ###
