"""Create TokenData

Revision ID: 68b6d9a7c8cd
Revises: bb9da1ffdd9e
Create Date: 2024-08-08 22:26:30.125385

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68b6d9a7c8cd'
down_revision = 'bb9da1ffdd9e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('token_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=100), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('price_source', sa.String(length=100), nullable=True),
    sa.Column('tot_supply', sa.Float(), nullable=True),
    sa.Column('circ_supply', sa.Float(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('token_data')
    # ### end Alembic commands ###
