"""Add supply column to Stablecoin

Revision ID: 75408d82f069
Revises: a2b703c9e9b5
Create Date: 2024-07-22 16:18:42.168650

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '75408d82f069'
down_revision = 'a2b703c9e9b5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stablecoin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('supply', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('circulating', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('pegged_against', sa.String(20), nullable=False, server_default='USD'))
        batch_op.add_column(sa.Column('info', sa.String(20), nullable=False, server_default=''))

    # Remove the default values
    with op.batch_alter_table('stablecoin', schema=None) as batch_op:
        batch_op.alter_column('pegged_against', server_default=None)
        batch_op.alter_column('info', server_default=None)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stablecoin', schema=None) as batch_op:
        batch_op.drop_column('supply')
        batch_op.drop_column('circulating')
        batch_op.drop_column('pegged_against')
        batch_op.drop_column('info')
    # ### end Alembic commands ###
