"""Add entity column to Stablecoin

Revision ID: a2b703c9e9b5
Revises: cacd02545397
Create Date: 2024-07-22 16:14:01.637573

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'a2b703c9e9b5'
down_revision = 'cacd02545397'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stablecoin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('entity', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stablecoin', schema=None) as batch_op:
        batch_op.drop_column('entity')
    # ### end Alembic commands ###
