"""Initial migration.

Revision ID: bf60f00425af
Revises:
Create Date: 2024-07-10 15:18:42.894239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bf60f00425af'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('money_market_rate',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('protocol', sa.String(length=15), nullable=False),
    sa.Column('token', sa.String(length=10), nullable=False),
    sa.Column('liquidity_rate', sa.Float(), nullable=False),
    sa.Column('borrow_rate', sa.Float(), nullable=False),
    sa.Column('chain', sa.String(length=20), nullable=False),
    sa.Column('tvl', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('money_market_rate')
    # ### end Alembic commands ###
