"""Add timestamp to MoneyMarketRate

Revision ID: c37d67cd5d9e
Revises: 
Create Date: 2024-07-04 20:32:53.829828

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c37d67cd5d9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money_market_rate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('timestamp', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money_market_rate', schema=None) as batch_op:
        batch_op.drop_column('timestamp')

    # ### end Alembic commands ###
