"""Add JSON column for collateral

Revision ID: cacd02545397
Revises: 5a8bdc0d87c8
Create Date: 2024-07-18 10:47:26.007292

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'cacd02545397'
down_revision = '5a8bdc0d87c8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money_market_rate', schema=None) as batch_op:
        batch_op.alter_column('collateral',
               existing_type=sa.VARCHAR(length=50),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True,
               postgresql_using='collateral::json')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('money_market_rate', schema=None) as batch_op:
        batch_op.alter_column('collateral',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.VARCHAR(length=50),
               existing_nullable=True,
               postgresql_using='collateral::varchar')

    # ### end Alembic commands ###
