"""Added columns to TokenData Table

Revision ID: d44c13db9f97
Revises: 68b6d9a7c8cd
Create Date: 2024-08-25 14:01:34.500086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd44c13db9f97'
down_revision = '68b6d9a7c8cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_data', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tvl', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('revenue', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('token_data', schema=None) as batch_op:
        batch_op.drop_column('revenue')
        batch_op.drop_column('tvl')

    # ### end Alembic commands ###
